<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="small-title"><?php echo $this->lang->_('FIELD'); ?><?php echo $this->fieldName; ?></div>
            <div class="title"><?php echo $this->lang->_('ADD_GROUP'); ?></div>
        </div>
    </div>
    <div id="error-box" class="error-custom">
        <?php if(isset($this->flashmsgs)) { ?>
            <?php   foreach($this->flashmsgs as $msg){
                        echo $msg;
        } } ?>
    </div>
    <?php if ($this->acl->isAllowed($this->userRole,'managegroups','edit')):?>
    <!--Groups Tables-->
    <div class="form-group"><br></div>
    <form id="addgroup-form"
            name="<?php echo $this->form->getName() ?>" 
            method="<?php echo $this->form->getMethod(); ?>"  
            action="<?php echo $this->form->getAction(); ?>"
            enctype="<?php echo $this->form->getAttrib('enctype'); ?>"
            role="form">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="form-group">
                    <?php echo $this->form->groupName; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->color; ?>
                </div>
                <br>
                <div class="form-group">
                    <?php echo $this->form->submit; ?>
                </div>
            </div>
        </div>
    </form>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
</div>