<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('MANAGE_STUDENTS'); ?></div>
        </div>
    </div>
    </div>
    <?php if ($this->acl->isAllowed($this->userRole,'managegroups','edit')):?>
    <!--Groups Tables-->
    <div class="row">
        <div class="students-doc">
            <?php foreach ($this->students as $s) : ?>
            <div class="col-xs-6 col-md-3 text-center">
                <div class="icon col-xs-6 col-md-3">
                    <span class="manage-student"><img src="<?php echo $this->baseUrl(); ?>/images/students/student.png" class="" alt="" /></span>
                    <div class="manage-student small-title"><?php echo $s['studentName']; ?></div>
                </div>
            </div>
            <?php endforeach; ?>
            
        </div>
    </div>
    <div class="form-group add-student">
        <div class="col-xs-4">
            <div class="form-group">
                <a href="<?php echo $this->baseurl(); ?>/managegroups/addtogroup/g/<?php echo $this->groupID ?>" class="btn btn-next-action"><img src="<?php echo $this->baseUrl(); ?>/images/add.png" alt="next" /><span><?php echo $this->lang->_('ADD_STUDENT'); ?></span></a>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="form-group">
                <a href="<?php echo $this->baseurl(); ?>/managegroups/deletestudents/g/<?php echo $this->groupID ?>" class="btn btn-next-action"><img src="<?php echo $this->baseUrl(); ?>/images/add.png" alt="next" /><span><?php echo $this->lang->_('DELETE_STUDENT'); ?></a>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="form-group">
                <a href="<?php echo $this->baseurl(); ?>/managegroups" class="btn btn-finish"><img src="<?php echo $this->baseUrl(); ?>/images/save.png" alt="save" /><span><?php echo $this->lang->_('FINISH'); ?></span></a>
            </div>
        </div>
    </div>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
</div>