<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="small-title"><?php echo $this->lang->_('FIELD'); ?><?php echo $this->fieldName; ?></div>
            <div class="title"><?php echo $this->lang->_('IMPORT_FROM_FIELD'); ?></div>
        </div>
    </div>
    <?php if ($this->acl->isAllowed($this->userRole,'managegroups','edit')):?>
    <!--Fields Tables-->
    <div class="row">
        <table class="table table-groups">
            <tbody>
                <?php foreach ($this->fields as $f) : ?>
                <tr>
                    <?php if ($f['fieldID'] != $this->fieldID): ?>
                    <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/games/memory.png" class="" alt="" /></td>
                    <td class="body" ng-click="field = <?php echo $f['fieldID']; ?>" ng-class="{'active' : field == <?php echo $f['fieldID']; ?>}"><a href="<?php echo $this->baseurl(); ?>/managegroups/importgroups/f/<?php echo $f['fieldID']; ?>"><div class="big-title"><?php echo $f['name']; ?></div></a></td>
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
</div>
