<div class="container-fluid progress-body">
    <!--Title-->
    <div class="row">
        <div class="second-header progress-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="small-title"><?php echo $this->lang->_('FIELD'); ?><?php echo $this->fieldName; ?></div>
            <div class="title"><?php echo $this->lang->_('SPEC_GROUP_PROGRESS'); ?><?php echo isset($this->group_name) ? ' ' . $this->group_name : ' '; ?></div>
        </div>
    </div>
    <?php if ($this->acl->isAllowed($this->userRole,'groups','read')):?>
    <!--Groups Tables-->
    <div class="row">
        <div class="student-doc">
            <?php if (!isset ($this->field_error)) : ?>
                <?php if (isset($this->plans) && $this->plans) : ?>
                <?php foreach ($this->plans as $p) : ?>
                <div class="col-xs-12 body">
                    <div class="pull-right">
                        <h4><?php echo $p['game_name']; ?></h4>
                        <p><?php echo $p['recommendation'] ?></p>
                    </div>
                    <div class="pull-left">
                        <span class="date"><?php echo $p['date']; ?></span>
                    </div>
                </div>
                <?php endforeach; ?>
                <?php else : ?>
                <div class="col-xs-12 body">
                    <?php echo $this->lang->_('NO_GROUP_PROGRESS_RESULTS'); ?>
                </div>
                <?php endif; ?>
            <?php else: ?>
                <?php echo $this->lang->_('NO_FIELD_CHOSEN'); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
<br>
<?php if (!isset ($this->field_error)) : ?>
<div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
    <div class="form-group">
        <a href="<?php echo $this->baseurl(); ?>/groups/report/g/<?php echo $this->groupID; ?>" class="btn btn-finish"><img src="<?php echo $this->baseUrl(); ?>/images/report.png" alt="next" /><span><?php echo $this->lang->_('STUDENT_REPORT'); ?></a>
    </div>
</div>
<?php endif; ?>
<?php else: ?>
    <?php echo $this->lang->_('ACCESS_DENIED'); ?>
<?php endif;?>
