<div class="container-fluid progress-body">
    <!--Title-->
    <div class="row">
        <div class="second-header progress-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('SPEC_GROUP_PROGRESS'); ?><?php echo isset($this->group_name) ? ' ' . $this->group_name : ' '; ?></div>
        </div>
    </div>
    <!--Groups Tables-->
    <div class="row">
        <div class="student-doc">
            <?php if (isset($this->plans) && $this->plans) : ?>
            <?php foreach ($this->plans as $p) : ?>
            <div class="col-xs-12 body">
                <div class="pull-right">
                    <h4><?php echo $p['game_name']; ?></h4>
                    <p><?php echo $p['recommendation'] ?></p>
                </div>
                <div class="pull-left">
                    <span class="date"><?php echo $p['date']; ?></span>
                </div>
            </div>
            <?php endforeach; ?>
            <?php else : ?>
            <div class="col-xs-12 body">
                <?php echo $this->lang->_('NO_GROUP_PROGRESS_RESULTS'); ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
