<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('MANAGE_STUDENTS'); ?></div>
        </div>
    </div>
    </div>
    <!--Groups Tables-->
    <div class="row">
        <div class="students-doc">
            <?php foreach ($this->students as $s) : ?>
            <div class="col-xs-6 col-md-3 text-center">
                <div class="icon col-xs-6 col-md-3">
                    <span class="manage-student">
                    <a href="<?php echo $this->baseurl(); ?>/manageGroups/deletestudent/s/<?php echo $s['studentID']; ?>/g/<?php echo $this->groupID; ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/images/students/student.png" class="" alt="" /></a>
                    </span>
                    <div class="manage-student small-title"><?php echo $s['studentName']; ?></div>
                </div>
            </div>
            <?php endforeach; ?>
            
        </div>
    </div>
    <div class="form-group add-student">
        <a href="<?php echo $this->baseurl(); ?>/manageGroups/addtogroup/g/<?php echo $this->groupID ?>" class="btn btn-add-student" style="width: 50%; color: #fff;"><img src="<?php echo $this->baseUrl(); ?>/images/add.png" alt="add" /><span><?php echo $this->lang->_('ADD_STUDENT'); ?></span></a>
    </div>
</div>