<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('ADD_STUDENT'); ?></div>
        </div>
    </div>
    <div id="error-box" class="error-custom">
        <?php if(isset($this->flashmsgs)) { ?>
            <?php   foreach($this->flashmsgs as $msg){
                        echo $msg;
        } } ?>
    </div>
    <?php if ($this->acl->isAllowed($this->userRole,'managestudents','edit')):?>
    <!--Groups Tables-->
    <div class="form-group"><br></div>
    <form id="add-form"
            name="<?php echo $this->form->getName() ?>" 
            method="<?php echo $this->form->getMethod(); ?>"  
            action="<?php echo $this->form->getAction(); ?>"
            enctype="<?php echo $this->form->getAttrib('enctype'); ?>"
            role="form">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="form-group">
                    <?php echo $this->form->studentName; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->studentLastName; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->gender; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->birthDate; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->motherName; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->motherPhone; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->fatherName; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->fatherPhone; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->form->idNumber; ?>
                </div>
                <br>
                <div class="form-group">
                    <?php echo $this->form->submit; ?>
                </div>
            </div>
        </div>
    </form>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
</div>