<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('DELETE_STUDENT'); ?></div>
        </div>
    </div>
    </div>
    <!--Groups Tables-->
    <div class="row">
        <div class="students-doc">
            <?php foreach ($this->students as $s) : ?>
            <div class="col-xs-6 col-md-3 text-center">
                <div class="icon col-xs-6 col-md-3">
                    <span class="manage-student">
                    <a href="<?php echo $this->baseurl(); ?>/managestudents/deletestudent/s/<?php echo $s['studentID']; ?>">
                    <img src="<?php echo $this->baseUrl(); ?>/images/students/student.png" class="" alt="" /></a>
                    </span>
                    <div class="manage-student small-title"><?php echo $s['studentName']; ?></div>
                </div>
            </div>
            <?php endforeach; ?>
            
        </div>
    </div>
</div>