<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('SELECT_FIELD'); ?></div>
        </div>
    </div>
    <!--Fields Tables-->
    <?php if ($this->acl->isAllowed($this->userRole,'fields','read')):?>
    <div class="row">
        <table class="table table-groups">
            <tbody>
                <?php foreach ($this->fields as $f) : ?>
                <tr>
                    <?php if(!$f['icon']): ?>
                        <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/games/memory.png" class="" alt="" /></td>
                    <?php else: ?>
                        <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/fields/<?php echo $f['icon']; ?>" class="" alt="" /></td>
                    <?php endif; ?>
                    <td class="body" ng-click="field = <?php echo $f['fieldID']; ?>" ng-class="{'active' : field == <?php echo $f['fieldID']; ?>}"><a href="<?php echo $this->baseurl(); ?>/groups/index/f/<?php echo $f['fieldID']; ?>"><div class="big-title"><?php echo $f['name']; ?></div></a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
</div>
