<div class="container-fluid">
    <div class="selected-group">
        <!--Big Icon-->
        <div class="row">
            <div class="big-icon text-center">
                <img src="<?php echo $this->baseUrl(); ?>/images/groups/group_blue.png" class="" alt="group_blue" />
            </div>
        </div>
        <div class="row">
            <div class="body text-center">
                <h3>ברוכים הבאים!</h3>
                <br>
                <br>
            </div>
        </div>
        <!--Actions-->
        <div class="row">
            <div class="col-xs-0 col-md-3"></div>
            <div class="col-xs-6 col-md-3">
                <div class="form-group">
                    <a href="<?php echo $this->baseurl(); ?>/entry/admin" class="btn btn-planning"><img src="<?php echo $this->baseUrl(); ?>/images/ADMIN_HEADER.png" alt="save" /><span><?php echo $this->lang->_('ADMIN_ENTRY'); ?></span></a>
                </div>
            </div>
            <div class="col-xs-6 col-md-3">
                <div class="form-group">
                    <a href="<?php echo $this->baseurl(); ?>/entry/user" class="btn btn-next-action"><img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" alt="next" /><span><?php echo $this->lang->_('USER_ENTRY'); ?></a>
                </div>
            </div>
            <div class="col-xs-0 col-md-3"></div>
        </div>
    </div>
</div>
