<div class="container-fluid progress-body">
    <!--Title-->
    <div class="row">
        <div class="second-header progress-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="small-title"><?php echo $this->lang->_('FIELD'); ?><?php echo $this->fieldName; ?></div>
            <div class="title"><?php echo $this->lang->_('GROUP_PROGRESS'); ?></div>
        </div>
    </div>
    <?php if ($this->acl->isAllowed($this->userRole,'planning','read')):?>
    <!--Groups Tables-->
    <div class="row">
        <table class="table table-groups">
            <tbody>
            <?php if(!isset($this->field_error)): ?>
                <?php foreach ($this->groups as $g) : ?>
                <tr>
                    <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/groups/group_<?php echo $g['color']; ?>.png" class="" alt="group_<?php echo $g['color']; ?>" /></td>
                    <td class="body" ng-click="group = <?php echo $g['groupID']; ?>" ng-class="{'active' : group == <?php echo $g['groupID']; ?>}"><a href="<?php echo $this->baseurl(); ?>/groups/progress/g/<?php echo $g['groupID']; ?>"><div class="big-title"><?php echo $g['name']; ?></div><span class="small-title"><?php echo $g['students']; ?></span></a></td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td><?php echo $this->lang->_('NO_FIELD_CHOSEN'); ?></td></tr>
            <?php endif;?>
            </tbody>
        </table>
    </div>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
</div>