<div class="container-fluid">
    <div class="goals ng-scope" data-ng-controller="Games">
        <!--Title-->
        <div class="row">
            <div class="second-header">
                <img src="<?php echo $this->baseUrl(); ?>/images/GROUP_HEADER.png" class="" alt="GROUP_HEADER" />
                <div class="title"><?php echo $this->lang->_('PLANNED_ACTIVITIES'); ?></div>
            </div>
        </div>
    <?php if ($this->acl->isAllowed($this->userRole,'planning','read')):?>
        <!--Groups Tables-->
        <div class="row">
            <table class="table table-groups">
                <tbody>
                    <?php if (!isset ($this->field_error)): ?>
                        <?php foreach ($this->groups as $g) : ?>
                            <?php if (isset($g['plan'])) : ?>
                            <tr>
                                <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/groups/group_<?php echo $g['color']; ?>.png" class="" alt="group_<?php echo $g['color']; ?>" /></td>
                                <td class="body" ng-click="group = <?php echo $g['groupID']; ?>" ng-class="{'active' : group == <?php echo $g['groupID']; ?>}"><a href="<?php echo $this->baseurl(); ?>/documentation/students/g/<?php echo $g['groupID']; ?>"><div class="big-title"><?php echo $g['name']; ?></div><span class="small-title"><b><?php echo $g['goal']; ?>:</b> <?php echo $g['plan']; ?></span></a></td>
                            </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php else: ?>
                            <tr><td><?php echo $this->lang->_('NO_FIELD_CHOSEN'); ?></td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
    </div>
</div>