<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <div class="small-title"><?php echo $this->lang->_('FIELD').$this->fieldName; ?> > <?php echo $this->lang->_('GROUP').$this->groupName; ?></div>
            <div class="title"><?php echo $this->lang->_('SELECT_GROUP'); ?></div>
        </div>
    </div>
    <?php if ($this->acl->isAllowed($this->userRole,'planning','read')):?>
        <!--Plans Tables-->
        <div class="row">
            <table class="table table-games">
                <tbody>
                    <?php foreach ($this->plans as $p) : ?>
                    <tr>
                        <td class="body middle" >
                            <a href="<?php echo $this->baseurl(); ?>"></a><div class="big-title"><?php echo $p['game_name']; ?></div></a>
                        </td>
                    </tr> 
                    <?php endforeach; ?>
                </tbody> 
            </table>
        </div>
    <?php else: ?>
        <?php echo $this->lang->_('ACCESS_DENIED'); ?>
    <?php endif;?>
    </div>
</div>
