<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/ADMIN_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('ADMIN_EDIT_GAME'); ?></div>
        </div>
    </div>
    <div id="error-box" class="error-custom">
        <?php if(isset($this->flashmsgs)) { ?>
            <?php   foreach($this->flashmsgs as $msg){
                        echo $msg;
        } } ?>
    </div>
    <!--Groups Tables-->
    <div class="form-group"><br></div>
    <form id="addgame-form"
            name="<?php echo $this->form->getName() ?>" 
            method="<?php echo $this->form->getMethod(); ?>"  
            action="<?php echo $this->form->getAction(); ?>"
            enctype="<?php echo $this->form->getAttrib('enctype'); ?>"
            role="form">
        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <div class="form-label"><?php echo $this->lang->_('GAMENAME'); ?></div>
                    <?php echo $this->form->gameName; ?>
                </div>
                <div class="form-label"><?php echo $this->lang->_('FORM_FILE'); ?></div>
                <input type="file" name="photo" id="fileSelect">
                <br>
                <div class="form-group col-md-4 col-md-offset-4">
                    <?php echo $this->form->submit; ?>
                </div>
            </div>
        </div>
    </form>
</div>