<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/ADMIN_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('ADMIN_EDIT_GOAL'); ?></div>
        </div>
    </div>
    <div id="error-box" class="error-custom">
        <?php if(isset($this->flashmsgs)) { ?>
            <?php   foreach($this->flashmsgs as $msg){
                        echo $msg;
        } } ?>
    </div>
    <!--Groups Tables-->
    <div class="form-group"><br></div>
    <form id="addgoal-form"
            name="<?php echo $this->form->getName() ?>" 
            method="<?php echo $this->form->getMethod(); ?>"  
            action="<?php echo $this->form->getAction(); ?>"
            enctype="<?php echo $this->form->getAttrib('enctype'); ?>"
            role="form">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="form-group">
                    <?php echo $this->form->goalName; ?>
                </div>
                <?php if(isset($this->goalID_parent)) : ?>
                    <div class="form-group">
                        <?php echo $this->form->goalLevel; ?>
                    </div>
                    <br>
                    <div class="form-group">
                        <?php echo $this->form->grade1; ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->form->grade2; ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->form->grade3; ?>
                    </div>
                     <div class="form-group">
                        <?php echo $this->form->grade4; ?>
                    </div>
                <?php else: ?>
                    <input type="file" name="photo" id="fileSelect">
                <?php endif; ?>
                <br>
                <div class="form-group">
                    <?php echo $this->form->submit; ?>
                </div>
            </div>
        </div>
    </form>
</div>