<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/ADMIN_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('ADMIN_MANAGE_GAN'); ?> : <?php echo $this->ganName?></div>
        </div>
    </div>
    <input type="hidden" id="base_url" value="<?php echo $this->baseUrl(); ?>">
    <input type="hidden" id="are_you_sure" value="<?php echo $this->lang->_('ARE_YOU_SURE_QUESTION'); ?>">
    <div class="row">
        <table class="table table-groups">
            <tbody>
                <?php foreach ($this->users as $u) : ?>
                <tr>
                    <td class="body"><div class="big-title"><?php echo $u['email']; ?></div></a></td>
                    <td class="delete"><br><button onclick="deleteuser('<?php echo $u['userID']; ?>','<?php echo $this->ganID; ?>')"><img src="<?php echo $this->baseUrl(); ?>/images/delete.png" class="" alt="" /></button></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="form-group add-student">
            <a href="<?php echo $this->baseurl(); ?>/admin/adduser/g/<?php echo $this->ganID; ?>" class="btn btn-add-student" style="width: 50%; color: #fff;"><img src="<?php echo $this->baseUrl(); ?>/images/add.png" alt="add" /><span><?php echo $this->lang->_('ADMIN_ADD_USER'); ?></span></a>
        </div>
    </div>
</div>
