<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/ADMIN_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('ADMIN_GAMES'); ?></div>
        </div>
    </div>
    <input type="hidden" id="base_url" value="<?php echo $this->baseUrl(); ?>">
    <input type="hidden" id="are_you_sure" value="<?php echo $this->lang->_('ARE_YOU_SURE_QUESTION'); ?>">
    <div class="row">
        <table class="table table-groups">
            <tbody>
                <?php foreach ($this->games as $g) : ?>
                <tr>
                    <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/games/<?php echo $g['icon']; ?>.png" class="" alt="" /></td>
                    <td class="body"><div class="big-title"><?php echo $g['name']; ?></div></td>
                    <td class="delete"><br><a href="<?php echo $this->baseurl(); ?>/admin/editgame/g/<?php echo $this->goalID; ?>/gm/<?php echo $g['gameID']; ?>" class=""><img src="<?php echo $this->baseUrl(); ?>/images/edit.png" alt="" /></a></td>
                    <td class="delete"><br><button onclick="deletegame('<?php echo $g['gameID']; ?>')"><img src="<?php echo $this->baseUrl(); ?>/images/delete.png" class="" alt="" /></button></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="col-xs-0 col-md-3"></div>
    <div class="col-xs-6 col-md-3">
        <div class="form-group">
            <a href="<?php echo $this->baseurl(); ?>/admin/addgame/g/<?php echo $this->goalID; ?>" class="btn btn-add-student"><img src="<?php echo $this->baseUrl(); ?>/images/add.png" alt="add" /><span><?php echo $this->lang->_('ADMIN_ADD_GAME'); ?></span></a>
        </div>
    </div>
    <div class="col-xs-6 col-md-3">
        <div class="form-group">
            <a href="<?php echo $this->baseurl(); ?>/admin/fields" class="btn btn-finish"><img src="<?php echo $this->baseUrl(); ?>/images/save.png" alt="save" /><span><?php echo $this->lang->_('FINISH'); ?></span></a>
        </div>
    </div>
    <div class="col-xs-0 col-md-3"></div>
</div>
