<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/ADMIN_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('ADMIN_GAMES'); ?></div>
        </div>
    </div>
    <input type="hidden" id="base_url" value="<?php echo $this->baseUrl(); ?>">
    <input type="hidden" id="are_you_sure" value="<?php echo $this->lang->_('ARE_YOU_SURE_QUESTION'); ?>">
    <div class="row">
        <table class="table table-groups">
            <tbody>
                <?php foreach ($this->games as $g) : ?>
                <tr>
                    <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/games/<?php echo $g['icon']; ?>.png" class="" alt="" /></td>
                    <td class="body"><div class="big-title"><?php echo $g['name']; ?></div></td>
                    <td class="delete"><br><button onclick="deletegame('<?php echo $g['gameID']; ?>')"><img src="<?php echo $this->baseUrl(); ?>/images/delete.png" class="" alt="" /></button></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="form-group add-student">
            <a href="<?php echo $this->baseurl(); ?>/admin/addgame/g/<?php echo $this->goalID; ?>" class="btn btn-add-student" style="width: 50%; color: #fff;"><img src="<?php echo $this->baseUrl(); ?>/images/add.png" alt="add" /><span><?php echo $this->lang->_('ADMIN_ADD_GAME'); ?></span></a>
    </div>
</div>
