<div class="container-fluid">
    <!--Title-->
    <div class="row">
        <div class="second-header">
            <img src="<?php echo $this->baseUrl(); ?>/images/ADMIN_HEADER.png" class="" alt="GROUP_HEADER" />
            <div class="title"><?php echo $this->lang->_('ADMIN_WELCOME'); ?></div>
        </div>
    </div>
    <input type="hidden" id="base_url" value="<?php echo $this->baseUrl(); ?>">
    <input type="hidden" id="are_you_sure" value="<?php echo $this->lang->_('ARE_YOU_SURE_QUESTION'); ?>">
    <div class="row">
        <table class="table table-groups">
            <tbody>
                <?php foreach ($this->gans as $g) : ?>
                <tr>
                    <td class="icon"><img src="<?php echo $this->baseUrl(); ?>/images/home.png" class="" alt="" /></td>
                    <td class="body"><a href="<?php echo $this->baseurl(); ?>/admin/editgan/g/<?php echo $g['ganID']; ?>"><div class="big-title"><?php echo $g['name']; ?></div></a></td>
                    <td class="delete"><br><a href="<?php echo $this->baseurl(); ?>/admin/editganname/g/<?php echo $g['ganID']; ?>" class=""><img src="<?php echo $this->baseUrl(); ?>/images/edit.png" alt="" /></a></td>
                    <td class="delete"><br><button onclick="deletegan('<?php echo $g['ganID']; ?>')"><img src="<?php echo $this->baseUrl(); ?>/images/delete.png" class="" alt="" /></button></td>

                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
